# Generated by Django 3.2 on 2022-08-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_userlibrary_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlibrary",
            name="adress",
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
