# Generated by Django 3.2 on 2022-08-02 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[("avalible", "avalible"), ("occupied", "occupied")],
                default="avalible",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="status",
            field=models.CharField(
                choices=[("active", "active"), ("inactive", "inactive")],
                default="ac",
                max_length=15,
            ),
        ),
    ]
