# Generated by Django 3.2 on 2022-08-03 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelf", "0001_initial"),
        ("book", "0002_auto_20220801_2134"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="shelf",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="shelf.shelf"
            ),
            preserve_default=False,
        ),
    ]
