# Generated by Django 3.2 on 2022-07-29 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_author_bookcopy_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookCopy',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='data_puplicate',
            new_name='date_puplicate',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='subject',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='book.author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(default='available', max_length=15),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(default='available', max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.category'),
        ),
    ]
