# Generated by Django 3.2 on 2022-08-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_book_book_copy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="book_copy",
        ),
        migrations.AddField(
            model_name="book",
            name="numCopies",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
