# Generated by Django 3.2 on 2022-08-03 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_auto_20220803_1150"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="numCopies",
        ),
    ]
