# Generated by Django 3.2 on 2022-08-04 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_copy", "0008_remove_bookcopy_book"),
        ("book", "0006_remove_book_numcopies"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="book_copy",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="book_copy.bookcopy",
            ),
            preserve_default=False,
        ),
    ]
