# Generated by Django 3.2 on 2022-08-04 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_book_book_copy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="book_copy",
        ),
    ]
