# Generated by Django 3.2 on 2022-08-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0009_auto_20220806_2355"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                default=1, help_text="13", max_length=13, verbose_name="ISBN"
            ),
            preserve_default=False,
        ),
    ]
