# Generated by Django 3.2 on 2022-08-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0011_auto_20220807_0058"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="dirty_isbn",
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(help_text="13", max_length=13, verbose_name="ISBN"),
        ),
    ]
