# Generated by Django 3.2 on 2022-08-03 02:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_auto_20220801_2134"),
        ("shelf", "0001_initial"),
        ("book_copy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookcopy",
            options={"ordering": ["due_back"]},
        ),
        migrations.AddField(
            model_name="bookcopy",
            name="book",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="book.book"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookcopy",
            name="due_back",
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bookcopy",
            name="shelf",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="shelf.shelf"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookcopy",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Maintenance"),
                    ("o", "On loan"),
                    ("a", "Available"),
                    ("r", "Reserved"),
                ],
                default="m",
                help_text="Book availability",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="bookcopy",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique ID for this particular book across whole library",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
