# Generated by Django 3.2 on 2022-08-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_copy", "0002_auto_20220802_2119"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcopy",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("a", "Available"), ("r", "Reserved")],
                default="a",
                help_text="Book availability",
                max_length=1,
            ),
        ),
    ]
