# Generated by Django 3.2 on 2022-08-03 16:50

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_auto_20220803_1150"),
        ("book_copy", "0006_auto_20220802_2205"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookcopy",
            options={"ordering": ["due_back"]},
        ),
        migrations.RemoveField(
            model_name="bookcopy",
            name="name",
        ),
        migrations.AddField(
            model_name="bookcopy",
            name="book",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="book.book"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bookcopy",
            name="due_back",
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="bookcopy",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("a", "Available"), ("r", "Reserved")],
                default="a",
                help_text="Book availability",
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="bookcopy",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                help_text="Unique ID for this particular book across whole library",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
