# Generated by Django 3.2 on 2022-08-04 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_copy", "0007_auto_20220803_1150"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookcopy",
            name="book",
        ),
    ]
