# Generated by Django 3.2 on 2022-08-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_copy", "0008_remove_bookcopy_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcopy",
            name="book_item",
            field=models.TextField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
