# Generated by Django 3.2 on 2022-08-04 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0008_remove_book_book_copy"),
        ("book_copy", "0009_bookcopy_book_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookcopy",
            name="book_item",
        ),
        migrations.AddField(
            model_name="bookcopy",
            name="book",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="book.book"
            ),
            preserve_default=False,
        ),
    ]
