# Generated by Django 3.2 on 2022-08-07 05:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_copy", "0010_auto_20220803_2106"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookcopy",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
