# Generated by Django 3.2 on 2022-08-09 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book_copy", "0011_alter_bookcopy_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookcopy",
            options={},
        ),
        migrations.RenameField(
            model_name="bookcopy",
            old_name="id",
            new_name="uuid",
        ),
        migrations.CreateModel(
            name="BookCopyLybrary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deleted", models.DateTimeField(editable=False, null=True)),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                ("due_back", models.DateField(blank=True, max_length=100, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("a", "Available"), ("r", "Reserved")],
                        default="a",
                        help_text="Book availability",
                        max_length=1,
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="book_copy.bookcopy",
                    ),
                ),
                (
                    "userBook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
